version: '3.8'

services:
  app:
    build: .
    container_name: transcript-engine-app
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    working_dir: /app
    command: poetry run uvicorn transcript_engine.main:app --host 0.0.0.0 --port 8000 --reload

# Removed ollama service definition
# Removed volumes key 